### ISSUE TITLE
Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by tyronedougherty** [Snowulf/oktajs#2]
Using the following code:
```
const OktaAPI = require('oktajs');
const okta = new OktaAPI('XXX', 'YYY');

okta.users.list({ limit: 1}, true, function(users){
     res.json(users);
});
```
I get the correct json response from the HTTP request, however, I get an error stating that `Can't set headers after they are sent`, crashing the thread. Not sure what is going on since surely it shouldn't be touching the same req/res objects provided from Express JS. Here's the stack trace:

```
_http_outgoing.js:356
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/Users/tyronedougherty/projects/worker/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/Users/tyronedougherty/projects/worker/node_modules/express/lib/response.js:154:12)
    at ServerResponse.json (/Users/tyronedougherty/projects/worker/node_modules/express/lib/response.js:240:15)
    at /Users/tyronedougherty/projects/worker/tasks/users/import/okta-sync.js:10:13
    at handleResponse (/Users/tyronedougherty/projects/worker/node_modules/oktajs/lib/NetworkAbstraction.js:114:13)
    at Request._callback (/Users/tyronedougherty/projects/worker/node_modules/oktajs/lib/NetworkAbstraction.js:73:55)
    at Request.self.callback (/Users/tyronedougherty/projects/worker/node_modules/oktajs/node_modules/request/request.js:199:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/tyronedougherty/projects/worker/node_modules/oktajs/node_modules/request/request.js:1036:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/tyronedougherty/projects/worker/node_modules/oktajs/node_modules/request/request.js:963:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Anyone got any idea how this can be fixed?

**Comment by tyronedougherty** [comment]
After some investigation this is because the request with the `followLink` set as true will follow the pagination, calling the callback with every page as specified in the docs:

> calling the callback with each page

This seems a little confusing to me, not sure why you wouldn't just call the callback once all the pages have been loaded, but I have designed a solution around this now, watching for the pageEnd parameter to be `true`.

Hope this helps someone :)

**Comment by ShakataGaNai** [comment]
Sorry, just saw this (for all the emails GitHub DOES send, this wasn't one). You're probably right on your commentary - but glad you have something that works for you presently.
